name: marlin_sdk
description: An SDK to send GCode to Marlin-compatible devices.
version: 1.0.0+1
repository: https://github.com/sbordeyne/marlin_sdk
publish_to: 'pub.dev'
issue_tracker: https://github.com/sbordeyne/marlin_sdk/issues

environment:
  sdk: ^3.3.3

dependencies: {}

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
